#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: ab27b0e
#
Name     : R-uuid
Version  : 1.2.0
Release  : 68
URL      : https://cran.r-project.org/src/contrib/uuid_1.2-0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/uuid_1.2-0.tar.gz
Summary  : Tools for Generating and Handling of UUIDs
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: R-uuid-lib = %{version}-%{release}
Requires: R-uuid-license = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-uuid package.
Group: Libraries
Requires: R-uuid-license = %{version}-%{release}

%description lib
lib components for the R-uuid package.


%package license
Summary: license components for the R-uuid package.
Group: Default

%description license
license components for the R-uuid package.


%prep
%setup -q -n uuid
pushd ..
cp -a uuid buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1705423697

%install
export SOURCE_DATE_EPOCH=1705423697
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-uuid
cp %{_builddir}/uuid/inst/COPYING %{buildroot}/usr/share/package-licenses/R-uuid/16fd05e0c827f9372ff54c2a16b30353842a6df1 || :
cp %{_builddir}/uuid/src/COPYING %{buildroot}/usr/share/package-licenses/R-uuid/16fd05e0c827f9372ff54c2a16b30353842a6df1 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/uuid/COPYING
/usr/lib64/R/library/uuid/DESCRIPTION
/usr/lib64/R/library/uuid/INDEX
/usr/lib64/R/library/uuid/LICENSE
/usr/lib64/R/library/uuid/Meta/Rd.rds
/usr/lib64/R/library/uuid/Meta/features.rds
/usr/lib64/R/library/uuid/Meta/hsearch.rds
/usr/lib64/R/library/uuid/Meta/links.rds
/usr/lib64/R/library/uuid/Meta/nsInfo.rds
/usr/lib64/R/library/uuid/Meta/package.rds
/usr/lib64/R/library/uuid/NAMESPACE
/usr/lib64/R/library/uuid/NEWS
/usr/lib64/R/library/uuid/R/uuid
/usr/lib64/R/library/uuid/R/uuid.rdb
/usr/lib64/R/library/uuid/R/uuid.rdx
/usr/lib64/R/library/uuid/help/AnIndex
/usr/lib64/R/library/uuid/help/aliases.rds
/usr/lib64/R/library/uuid/help/paths.rds
/usr/lib64/R/library/uuid/help/uuid.rdb
/usr/lib64/R/library/uuid/help/uuid.rdx
/usr/lib64/R/library/uuid/html/00Index.html
/usr/lib64/R/library/uuid/html/R.css
/usr/lib64/R/library/uuid/include/Ruuid.h
/usr/lib64/R/library/uuid/include/uuid.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/uuid/libs/uuid.so
/usr/lib64/R/library/uuid/libs/uuid.so.avx2
/usr/lib64/R/library/uuid/libs/uuid.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-uuid/16fd05e0c827f9372ff54c2a16b30353842a6df1
